[package]
name = "rustclaw"
version = "1.1.3"
edition = "2024"
repository = "https://github.com/shimaenaga1123/rustclaw"
homepage = "https://github.com/shimaenaga1123/rustclaw"
description = "A lightweight, memory-aware Discord AI assistant powered by Anthropic-compatible APIs, implemented in Rust. Inspired by nanoclaw and OpenClaw"
license = "MIT"

[dependencies]
poise = "0.6"

rig-core = "0.30"

tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "sync", "time", "signal"] }
tokio-cron-scheduler = "0.15"
futures-util = "0.3"
async-trait = "0.1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

anyhow = "1"
thiserror = "2"

chrono = "0.4"
chrono-tz = "0.10.4"
iana-time-zone = "0.1.65"

uuid = { version = "1", features = ["v4"] }
reqwest = { version = "0.12", features = ["rustls-tls", "json"] }
bollard = "0.20"
typst = "0.14"
typst-render = "0.14"
typst-assets = { version = "0.14", features = ["fonts"] }
tiny-skia = "0.11"

fastembed = "5"
usearch = "2"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }

[profile.release]
strip = true
lto = "thin"
panic = "abort"
opt-level = "s"

[profile.dist]
inherits = "release"
