[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "homebrew"]
# Path that installers should place binaries in
install-path = "~/.local/share/rustclaw"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Whether to install an updater program
install-updater = true
# A GitHub repo to push Homebrew formulas to
tap = "shimaenaga1123/homebrew-tap"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]

[dist.dependencies.apt]
protobuf-compiler = '*'

[dist.dependencies.homebrew]
protobuf = '*'

[dist.dependencies.chocolatey]
protoc = '*'

[dist.github-custom-runners]
x86_64-unknown-linux-gnu = "ubuntu-24.04"
